### PR TITLE
Added support for customStringify

### PR DESCRIPTION
**Pull request by mariolyon**
Hi Trent, 

would you accept my change? the project that I'm working on requires simple key=value output, and also file rotation (and we are pretty much tied to using restify with bunyan, and the features it supports).

I tried using a raw stream together with the package bunyan-rotating-filestream, but it has bugs. 

Thanks
Mario

### CODE REVIEW

**Comment by mariolyon** [comment]
i'm closing this pull request, because i discovered that I can create a raw stream that writes to an instance of bunyan.RotatingFileStream.  I didn't know it possible from the docs, and realized it could be done only after reading the code. Thanks. I love the raw streams idea. Its so flexible.

**Comment by Khez** [comment]
@mariolyon doesn't the `serializers` option help in this scenario? it gives you a way to basically do customStringify

**Comment by mariolyon** [comment]
The serializers are for serializer individual fields in the log record. Records will still be outputted as JSON. 
Having a customStringify function, would allow the serialization of the entire record.

**Comment by Khez** [comment]
@mariolyon Ohh, you're trying to change how the log record... wouldn't that mean you break bunyan-cli ?

I know the issue is closed, but I'm interested in understanding the different use cases of bunyan within the community

**Pull request closed without merging**
