### PR TITLE
Fix issues to work with webpack

### LINKED ISSUE #213: Doesn't work with webpack
Module not found: Error: Cannot resolve module 'fs' in node_modules\bunyan\node_modules\mv\node_modules\mkdirp

The 2 modules that doesn't work are:

 - fs
 - dtrace-provider

https://github.com/trentm/node-bunyan/blob/2f95bb8091a8085756cc1f73c51dcf020f1990a2/lib/bunyan.js#L35

Look at: https://github.com/webpack/webpack/issues/689

### PR DESCRIPTION
**Pull request by DenisIzmaylov**
Please merge to resolve #213 (also discussed here https://github.com/webpack/webpack/issues/689 ).
Now it's possible to implement with `webpack` browser output:
```javascript
function BrowserStream() {}
BrowserStream.prototype.write = function (rec) {
  const method = bunyan.nameFromLevel[rec['level']];
  const fn = (method === 'fatal') ? console.log : console[method];
  fn.call(console, (rec['timestamp'] || new Date()).toISOString() + ' ' + rec['msg'], rec);
};

const logger = bunyan.createLogger({
  name: 'my-app',
  streams: [{
    stream: new BrowserStream(),
    level: 'trace',
    type: 'raw'
  }]
});

logger.debug("Isomorphic message", {"extra": "some-data"});
```

### CODE REVIEW

**Comment by DenisIzmaylov** [comment]
Up!

**Comment by HenriJ** [comment]
Please merge this PR. I'd love to be able to use bunyan with webpack !

**Comment by jfstephe** [comment]
+1

**Comment by davidgilbertson** [comment]
+1

It's not a good sign when (presumably) working PRs sit for months unpulled, I hope this isn't going the way of winston...

**Comment by DenisIzmaylov** [comment]
Up!

**Comment by trentm** [comment]
merged in commit 466829dc7307995508e3b2737b334f52ab4939a5
Thanks very much! My apologies for the delay in merging this. This'll be in bunyan@1.5.0 soon.

**Comment by davidgilbertson** [comment]
Nice one @trentm, thanks! I retract my snakry winston comment :)

**Comment by peter-mouland** [comment]
hey all, 
I'm still getting the following error : `Cannot resolve module 'fs'`

After reading https://github.com/webpack/webpack/issues/689, was the following meant to go into this PR or am i misunderstanding how to use it with webpack?
```json
// package.json
"browser": {
  "dtrace-provider": false,
  "fs": false
}
```

thanks

**Comment by davidgilbertson** [comment]
@peter-mouland Not sure about this fix (are you using 1.5?) but maybe putting this in your webpack config will get it running:
```javascript
    node: {
        fs: 'empty'
    }
```
Some more words: http://webpack.github.io/docs/configuration.html#node

**Pull request closed without merging**
