### PR TITLE
Upgrade to dtrace-provider 0.5.

### LINKED ISSUE #258: dtrace-provider unable to be installed on iojs 2.0.1 and 2.1.0
This isn't a bug with bunyan per se, but I'm getting a bunch of those superfluous errors when I start up my app:

```
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
```

Filed on node-dtrace-provider as [issue 64](https://github.com/chrisa/node-dtrace-provider/issues/64).

### PR DESCRIPTION
**Pull request by stephank**
Fixes #258.

Test results on iojs 1.8.1 with current master, and iojs 2.1.0 with this patch are the same. (I have 3 unrelated failures.)

### CODE REVIEW

**Comment by mcollina** [comment]
:+1:, will this be a patch release?

**Comment by johnhaley81** [comment]
This doesn't change any api or feature really but rather allows the module to be used in iojs. :+1:

**Comment by theturtle32** [comment]
+1

**Comment by trentm** [comment]
Thanks! Sorry for the delay. Should be in bunyan@1.4.0.

**Pull request closed without merging**
