### PR TITLE
Added inspectDepth option 

### PR DESCRIPTION
**Pull request by xantorres**
Added the inspectDepth option to the Logger options to allow recusive deep logging of big objects

### CODE REVIEW

**Comment by voxpelli** [comment]
Looks like you got some unrelated code changes into that commit? Trying to keep the code changes to a minimum certainly makes revieing easier + lessens the risk for any merge conflicts with other PR:s that are merged before or after yours.

**Comment by xantorres** [comment]
It looks like my IDE automatically did some code formatting that I did not notice before commiting the changes, now it should be ok. Thanks @voxpelli for the feedback,

**Comment by trentm** [comment]
Sorry for the delay! 

I like this. However, there is the *potential* (yes, slim chance) for this to be a compat issue if there is someone that has a `bunyan.createLogger` using `inspectDepth` already.

I was thinking a bit how we could make that transition work (and similar potential new createLogger/log.child options in the future):

```
// A new optional second {fields} object that is just raw fields, no special
// handling for options like 'streams', 'level', et al.
var log = bunyan.createLogger({opts-and-fields}[, {fields}]);

// Three possible call signatures for `log.child`.
var kid = log.child({opts-and-fields});           // already exists
var kid = log.child({fields}, true);              // already exists
var kid = log.child({opts-and-fields}, {fields}); // new signature, to match new `createLogger` second option
```

The new optional second `{fields}` argument allows users of Bunyan to
insulate against possible future additional options via:

```
var log = bunyan.createLogger({
    name: 'foo'
    streams: [...]
}, {
    fuzzy: 'wuzzy',
    ...
});
```

So adding `inspectDepth` would go like this:

1. release a bunyan 1.9 with the optional second `fields` arg
2. release a bunyan 2.0 with `inspectDepth` as a new option

**Comment by trentm** [comment]
https://github.com/trentm/node-bunyan/issues/460 added for the v1.9 part.

**Pull request closed without merging**
