### PR TITLE
Update moment version to 2.19.3, due to this security vulnerability

### PR DESCRIPTION
**Pull request by hiro5id**
Update moment version to 2.19.3, due to this security vulnerability: https://nodesecurity.io/advisories/532

### CODE REVIEW

**Comment by hiro5id** [comment]
I'm not really sure why the Travis CI is failing, can anyone help me here ?

**Comment by hiro5id** [comment]
can someone help me out with why the build is failing ? @trentm

**Comment by amorriscode** [comment]
No idea why the build fails but this is [a duplicate PR](https://github.com/trentm/node-bunyan/pull/558).

**Comment by trentm** [comment]
Thanks. I've merged effectively this change via https://github.com/trentm/node-bunyan/pull/558

(FYI on the delay in my responding: https://github.com/trentm/node-bunyan/issues/335#issuecomment-648583828)

**Pull request closed without merging**
